### PR TITLE
2018 Modern rewrite

### PR DESCRIPTION
**Pull request by craigerskine**
### Changes

**09/03/2018**  

* Complete rewrite
* Assets now fully compressed
* CSS is now responsive and functional using TailwindCSS
* Most data is templated via Vue.js
* Now uses a gulp build process which includes a mini web server that auto reloads as you edit the CSS, JS, HTML

### Usage

* Install node.js
* Clone repo
* Open a Terminal in the `/_src` folder
* Type: `npm install`
* Type: `./node_modules/.bin/gulp`
* Edit the code in the `/_src` folder to trigger the build process which moves the processed files to the `../` folder
* Content that could change often or that is repeatable is located in `/data.js`

### CODE REVIEW

**Comment by clobber** [comment]
Thanks! Just wondering, is there a way to maintain this without the dependencies of node/gulp and does node/gulp need to be installed server-side for this rewrite to be usable? An external build process and dependencies just seems a bit heavy for a website as ours. Asking since everything hosted via GitHub would need to be 'static'.

**Comment by clobber** [comment]
Ah nevermind - figured it out. That workflow seems like the best way to maintain it given current webdev trends. By the way, just sent you an invite to the org so you can make any changes on the fly if you want.

**Comment by craigerskine** [comment]
We should only ever need to update the data.js file for simple content changes like download links, version updates, new controllers support, cores, etc. The build process is only really for when we need to make layout or markup changes... which should be few and far between.

**Comment by clobber** [comment]
@craigerskine Heya, wanted to mention we have a Discord server set up if you want to follow development more closely: https://discord.gg/vgQqea

**Comment by craigerskine** [comment]
@clobber I missed this comment and the invite expired. Any chance I can get a new one?

**Comment by clobber** [comment]
@craigerskine Here you go: https://discord.gg/DqnUBj

**Comment by craigerskine** [comment]
@clobber I keep getting an invalid/expired error. How much time do they give you to redeem the code?

**Comment by clobber** [comment]
1 day. Message me back here when you get this and I will send another invite, but make sure you click it in time :P

**Pull request merged**
